### ISSUE TITLE
Add a Type Image in type DB

### ISSUE THREAD

**Issue by keerthanakumar** [keerthanakumar/cs373-imdb#45]

**Comment by fzohra** [comment]
Able to get the image urls for a place using the google api. Some places may have multiple images, we can store the urls for all of them using an association table. Thoughts?

**Comment by fzohra** [comment]
for images of the place, not icons

**Comment by ncrum** [comment]
No this is images of the type. Not place. An image for food, money, or nightclub, etc

**Comment by fzohra** [comment]
oh, got it that would just alter the existing Type table.

**Comment by fzohra** [comment]
but we still need pics for the places, so I'm thinking it will still be a good idea to create the M2M for it. I'm pulling data and given how its formatted it will be good to make the change now rather then later

**Comment by ncrum** [comment]
Yeah we might want to pull the photos now so we dont have to use google again
