### ISSUE TITLE
After creating script to query google for data, 'places' table should have around 5000-6000 records

### ISSUE THREAD

**Issue by ncrum** [keerthanakumar/cs373-imdb#50]
Math figured as: (96 Google supported types) x (~60 results per type) = 5760 records

**Comment by YunJang** [comment]
Hey Nick, are we getting 60 results per radius, prominence, and types query?

Or are we getting 20 results from each of those so that we end up with a total of 60?

**Comment by ncrum** [comment]
Well on average the max per supported type is 60, not considering the three different queries. Chances are we will have many duplicates. 96*60=5760. Though considering duplicated and doing the extra two query types I guestimated 5000-6000. Though maybe its more like 4000-5000.
